apiVersion: v2
name: cats-and-dogs
description: Camel Quarkus demo'ing cats-and-dogs
type: application
version: 1.0.0
appVersion: 1.0.0
kubeVersion: '>=1.20.0-0'
keywords:
- fuse
- quakrus
maintainers:
- name: garethahealy
