---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "cats-and-dogs.fullname" . }}-docker
  labels:
    {{- include "cats-and-dogs.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "cats-and-dogs.fullname" . }}-docker:latest
  runPolicy: Serial
  source:
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.jvm
