---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "cats-and-dogs.fullname" . }}-source
  labels:
    {{- include "cats-and-dogs.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "cats-and-dogs.fullname" . }}-source:latest
  runPolicy: Serial
  source:
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-17:1.14
    type: Source
