---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cats-and-dogs.fullname" . }}
  labels:
    {{- include "cats-and-dogs.labels" . | nindent 4 }}
data:
  application.properties: |
    quarkus.log.level=INFO
    
    # REST
    io.vertx.web.route.param.extended-pattern=true

    # OpenAPI
    quarkus.smallrye-openapi.path=/openapi
    quarkus.swagger-ui.path=/openapi-ui
    quarkus.swagger-ui.always-include=true

    # Datasource
    quarkus.datasource.db-kind=postgresql
    quarkus.datasource.username=quarkus
    quarkus.datasource.password=quarkus
    quarkus.datasource.jdbc.max-size=16
    quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql-db:5432/quarkus

    quarkus.hibernate-orm.database.generation = drop-and-create

    # JMS
    amqp-host=broker-amqp-0-svc
    amqp-port=5672
    quarkus.qpid-jms.url=amqp://${amqp-host}:${amqp-port}
    quarkus.qpid-jms.username=admin
    quarkus.qpid-jms.password=admin

    outgoing.queue=amqp:queue:outgoing