---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cats-and-dogs.fullname" . }}
  labels:
    {{- include "cats-and-dogs.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas.min }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "cats-and-dogs.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9779'
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "cats-and-dogs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Values.image_version }}
          imagePullPolicy: Always
          name: {{ include "cats-and-dogs.name" . }}
          startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '600m'
              memory: 1000Mi
            requests:
              cpu: '100m'
              memory: 100Mi
          volumeMounts:
            - name: config-volume
              mountPath: /deployments/config/application.properties
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "cats-and-dogs.fullname" . }}