{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "cats-and-dogs.fullname" . }}
  labels:
    {{- include "cats-and-dogs.labels" . | nindent 4 }}
spec:
  port:
    targetPort: tcp
  to:
    kind: Service
    name: {{ include "cats-and-dogs.fullname" . }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
{{ end }}
